version: '3'

services:
  db:
    image: mariadb:latest
    container_name: authentication-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: authentication
      MARIADB_USER: sathaphon
      MARIADB_PASSWORD: sathaphon1234
    ports:
      - "3380:3306"
    volumes:
      - ./database_data:/var/lib/mysql
